### ISSUE TITLE
多个页面来回切换，内存疯狂增加的问题

### ISSUE THREAD

**Issue by xsdream** [538832/vue-amap#1]
当在多个地图页面之间切换时，浏览器内存会一直增加。得不到释放。ji即使调用map.destroy（）也不行。
这是我工作中发现的问题，希望和你讨论，我研究了很长时间没有解决~
![image](https://user-images.githubusercontent.com/31870384/127511478-2befe3f3-6339-4f1c-ac00-6d7462adcf23.png)

**Comment by 538832** [comment]
你好，这个问题的原因是在&nbsp;加载JSAPI时（index.html中），采用的是直接加载 JSAPI 方式，并且一次加载了整个项目中所用的插件，可以采用&nbsp;JSAPI Loader加载方式&nbsp;(官方推荐)&nbsp;，插件按需加载，。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "538832/vue-amap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月29日(星期四) 晚上10:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[538832/vue-amap] 多个页面来回切换，内存疯狂增加的问题 (#1)





 
当在多个地图页面之间切换时，浏览器内存会一直增加。得不到释放。ji即使调用map.destroy（）也不行。
 这是我工作中发现的问题，希望和你讨论，我研究了很长时间没有解决~
